print("Twinkle, twinkle, little star,")
print("\tHow I wonder what you are! ")
print("\t\tUp above the world so high,")
print("\t\tLike a diamond in the sky.")
print("Twinkle, twinkle, little star,")
print("\tHow I wonder what you are! ")
